spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

os:
  client:
    secretId: ""
    secretKey: ""
    regin: ""
    bucketName: ""

alipay:
  application:
    serverUrl: ""
    appId: ""
    privateKey: ""
    alipayPublicKey: ""

server:
  address: 0.0.0.0
